SRCS = $(shell find -name '*.cpp')
OBJS = $(addsuffix .o,$(basename $(SRCS)))

INCLUDE = -I/usr/include/ -I../../include
HUGE_SDL = ../huge_sdl.a

CC = g++
CFLAGS = -Wall -std=c++11 $(INCLUDE)

all: $(OBJS) lib

%.o : %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

lib: $(OBJS)
	ar -rcs $(HUGE_SDL) $^

clean:
	rm $(OBJS)
	rm $(HUGE_SDL)

