SRCS = $(shell find -name '*.cpp')
OBJS = $(addsuffix .o,$(basename $(SRCS)))

INCLUDE = -I/usr/include/ -I../../include
LIBDIR  = -L/usr/X11R6/lib
LIBRARIES = -lX11 -lSDL2 -lGLEW -lGL -lGLU -lm -lSDL2_image

CC = g++
CFLAGS = -Wall -std=c++11 $(INCLUDE)
HUGE = ../../src/huge.a ../../src/huge_sdl.a ../../src/huge_opengl.a
HW = helloworld

$(HW): $(OBJS)
	$(CC) -o $@ $^ $(LIBDIR)$(LIBRARIES) $(HUGE)

%.o : %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm $(OBJS)
	rm $(HW)

